request_tracker/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("requests.urls"))
]

requests/urls.py
from django.conf.urls import url
from . import views

app_name = 'requests'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),

    #user's created tickets
    url(r'^tickets/$', views.TicketView.as_view(), name='tickets'),

    #user's tickets to be worked on
    url(r'^work/$', views.WorkView.as_view(), name='work'),

    #create a ticket
    url(r'^addticket/$', views.AddView.as_view(), name='addticket'),

    #view tickets
    url(r'^tickets/view/(?P<pk>[0-9]+)/$', views.TicketDetailView.as_view(), name='viewticket'),

]

requests/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models

class Queue(models.Model):
    name = models.CharField(max_length=50)
    workers = models.ManyToManyField(User, related_name='work_queues', blank=True)
    creators = models.ManyToManyField(User, related_name='create_queues', blank=True)
    everybody = models.BooleanField(default=False)

    def has_worker_rights(self, user):
        try:
            u = self.workers.get(pk=user.id)
        except User.DoesNotExist:
            return False
        else:
            if u:
                return True
            else:
                return False

    def has_creator_rights(self, user):
        if self.everybody:
            return True
        try:
            u = self.creators.get(pk=user.id)
        except User.DoesNotExist:
            return False
        else:
            if u:
                return True
            else:
                return False

    def get_open_tickets(self):
        tickets = self.ticket_set.all().exclude(status='C')
        return tickets

    def __str__(self):
        return self.name

status_choices = (
        ('N', 'New'),
        ('O', 'Open'),
        ('A', 'Assigned'),
        ('C', 'Closed'),
)

class Ticket(models.Model):
    subject = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    time = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(User, related_name='created_tickets')
    queue = models.ForeignKey(Queue, on_delete=models.CASCADE, null=True)

    status = models.CharField(max_length=10, choices=status_choices, default='N')

    def __str__(self):
        return self.creator.username + ": " + self.subject


    def get_lbtype(self):
        if self.status == 'N':
            return 'success'
        else:
            if self.status == 'O':
                return 'info'
            else:
                if self.status == 'A':
                    return 'primary'
                else:
                    if self.status == 'C':
                        return 'default'

class Update(models.Model):
    time = models.DateTimeField(auto_now=True)
    comment = models.CharField(max_length=500, null=True, blank=True)
    status = models.CharField(max_length=1, choices=status_choices, blank=True)
    ticket = models.ForeignKey(Ticket, related_name='updates', on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True)

    class Meta:
        ordering = ['-time']

    def __str__(self):
        return self.user.username + " " + self.time.__str__()

    def get_lbtype(self):
        if self.status == 'N':
            return 'success'
        else:
            if self.status == 'O':
                return 'info'
            else:
                if self.status == 'A':
                    return 'primary'
                else:
                    if self.status == 'C':
                        return 'default'

requests/forms.py
from django.contrib.auth.models import User
from django import forms

from requests.models import Ticket, Update


class UserForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    username = forms.CharField(widget = forms.TextInput(attrs={'placeholder': 'Username'}))

    class Meta:
        fields = ['username', 'password']

class AddTicketForm(forms.ModelForm):
    subject = forms.CharField(widget = forms.TextInput(attrs={'placeholder': 'Subject'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Detailed description of problem'}))


    class Meta:
        model = Ticket
        fields = ['subject', 'description', 'queue']

    def __init__(self, *args, **kwargs):
        qset = kwargs.pop('qset')
        super(AddTicketForm, self).__init__(*args, **kwargs)
        self.fields['queue'].queryset = qset


class UpdateForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Comment', 'style': 'width: 100%; height: 100px;'}))

    class Meta:
        model = Update
        fields = ['comment', 'status']

requests/views.py
from itertools import chain

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.views import View
from django.views import generic

from request_tracker import settings
from requests.forms import UserForm, AddTicketForm, UpdateForm
from requests.models import Queue, Ticket


class IndexView(generic.ListView):
    template_name = 'requests/index.html'
    context_object_name = 'all_queues'

    def get_queryset(self):
        #everyone = Queue.objects.filter(everybody=True)
        user = User.objects.get(pk=self.request.user.id)
        users_queues = user.work_queues.all();
        if user.is_staff: users_queues = Queue.objects.all()
        #result_list = list(everyone) + list(set(users_queues) - set(everyone))
        return users_queues

class LoginView(View):
    form_class = UserForm
    template_name = 'requests/login.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        print form.is_valid()
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('requests:index')
                else: return render(request, self.template_name, {'form': form, 'error': 'Your account has been disabled'})

            else: return render(request, self.template_name, {'form': form, 'error': 'Invalid username or password'})
        else: return render(request, self.template_name, {'form': form})

class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('requests:login')

class TicketView(generic.ListView):
    template_name = 'requests/tickets.html'
    context_object_name = 'tickets'

    def get_queryset(self):
        users_tickets = self.request.user.created_tickets.all()
        return users_tickets

class WorkView(generic.ListView):
    template_name = 'requests/work.html'
    context_object_name = 'queues'

    def get_queryset(self):
        user = User.objects.get(pk=self.request.user.id)
        users_queues = user.work_queues.all()
        if user.is_staff: users_queues = Queue.objects.all()
        return users_queues


class AddView(generic.FormView):
    form_class = AddTicketForm
    template_name = 'requests/addticket.html'

    def get(self, request):
        everyone = Queue.objects.filter(everybody=True)
        user = self.request.user
        users_queues = user.create_queues.all() | everyone
        if user.is_staff: users_queues = Queue.objects.all()
        #result_list = queryset(everyone) + list(set(users_queues) - set(everyone))

        form = self.form_class(qset=users_queues)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        everyone = Queue.objects.filter(everybody=True)
        user = self.request.user
        users_queues = user.create_queues.all() | everyone
        if user.is_staff: users_queues = Queue.objects.all()
        #result_list = queryset(everyone) + list(set(users_queues) - set(everyone))

        form = self.form_class(qset=users_queues, data=request.POST)

        if(form.is_valid()):
            ticket = form.save(commit=False)
            ticket.creator = User.objects.get(pk=request.user.id)

            ticket.save()

            notify_workers(ticket)

            return redirect('requests:tickets')

        return render(request, self.template_name, {'form': form})


def notify_workers(ticket):
    worker_list = []
    for u in ticket.queue.workers.all():
        worker_list.append(u.email)

    send_mail('Ticket [' + str(ticket.id) + '] - ' + ticket.subject,
              'Problem description:\n' + ticket.description + "\nFrom queue: " + ticket.queue.__str__(),
              settings.EMAIL_HOST_USER,
              worker_list,
              fail_silently=False)

class TicketDetailView(generic.DetailView):
    model = Ticket
    form_class = UpdateForm
    template_name = 'requests/ticket_view.html'

    def get(self, request, pk):
        ticket = Ticket.objects.get(pk=pk)
        if(ticket.status == 'N'):
            ticket.status = 'O'
            ticket.save()

        form = self.form_class(None)

        return render(request, self.template_name, {'ticket': ticket, 'form' : form})

    def post(self, request, pk):
        ticket = Ticket.objects.get(pk=pk)
        user = request.user
        form = self.form_class(request.POST)

        if(form.is_valid()):
            update = form.save(commit=False)
            update.user = user;
            update.ticket = ticket;

            if not form.data['status']:
                update.status = ticket.status

            if update.status != ticket.status:
                ticket.status = update.status
                ticket.save()

            update.save()
            if ticket.creator.email:
                send_mail('Ticket [' + str(ticket.id) + '] - ' + ticket.subject,
                        update.user.username + ":\n" +update.comment,
                        settings.EMAIL_HOST_USER,
                        [ticket.creator.email],
                        fail_silently=False)

        return render(request, self.template_name, {'ticket': ticket, 'form': form})

requests/templates/requests/addticket.html
{% extends 'requests/base.html' %}

{% block title %}Add New Ticket{% endblock %}

{% block body %}
<div class="container-fluid">

  <div class="row">
    <div class="col-sm-12 col-md-7">
      <div class="panel panel default">
        <div class="panel-body">
          <h1>Add Ticket</h1>

          <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'requests/form_template.html' %}
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
              </div>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

requests/templates/requests/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}Request Tracker{% endblock %}</title>

  {% load staticfiles %}
  <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'requests/style.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>

<body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'requests:index' %}">Request Tracking System</a>
      </div>

      <div class="collapse navbar-collapse" id="topNavBar">
         <ul class="nav navbar-nav">
             <li class="{% block yours %}{% endblock %}">
                 <a href="{% url 'requests:tickets' %}">
                     <span class="glyphicon glyphicon-tag"></span>&nbsp;Your Created Tickets
                 </a>
             </li>
             <li class="{% block work %}{% endblock %}">
                <a href="{% url 'requests:work' %}">
                    <span class="glyphicon glyphicon-wrench"></span>&nbsp;Tickets In Your Work Queues
                </a>
             </li>

         </ul>

         <ul class="nav navbar-nav navbar-right">

             <li>
                 <a href="{% url 'requests:addticket' %}">
                     <span class="glyphicon glyphicon-plus"></span>&nbsp;Create Ticket
                 </a>
             </li>

             {% if user.is_staff %}
             <li>
                 <a href="{% url 'admin:index' %}">
                     <span class="glyphicon glyphicon-console"></span>&nbsp;Admin Panel
                 </a>
             </li>
             {% endif %}

             <li>
                 <a href="{% url 'requests:logout' %}">
                     <span class="glyphicon glyphicon-off"></span>&nbsp;Logout
                 </a>
             </li>

         </ul>

      </div>

    </div>
  </nav>

  <div class="container-fluid">
  {% block body %}
  {% endblock %}
  </div>

</body>

</html>

requests/templates/requests/form_template.html
{% for field in form %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
  </div>
{% endfor %}

requests/templates/requests/index.html
{% extends 'requests/base.html' %}
{%  block title %}Homepage{% endblock %}


{% block body %}
    <div class="container-fluid">
        <h1 align="center">Support Request Tracking System</h1>
        <hr>

        <h3 align="center">You are logged in as {{ user.username }}</h3>
    </div>
{% endblock %}

requests/templates/requests/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login To Request Tracker</title>

    {% load staticfiles %}
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'requests/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="absolute-center is-responsive">
                <div class="col-sm-12 col-md-10 col-md-offset-1">
                    <form action="" method="POST" id="loginForm">
                        {%  csrf_token %}
                        <h3 style="text-align: center;">Please Login</h3>
                        <p align="center" style="color: red;">{{ error }}</p>
                        <div class="form-group input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            {{ form.username }}
                        </div>
                        <div class="form-group input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            {{ form.password }}
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-def btn-block">Login</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

requests/templates/requests/render_ticket.html
<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>{{ ticket.creator }}</strong>
            <span style="float:right;">
                <span class="label label-{{ ticket.get_lbtype }}">{{ ticket.get_status_display }}</span>
                {{ ticket.time }}
            </span>
        </div>

        <div class="panel-body" style="height: 150px; overflow: auto;">
            <h3>{{ ticket.subject }}</h3>
            <p>{{ ticket.description }}</p>
        </div>

        <div class="panel-footer" style="text-align: right;">
            <a href="{% url 'requests:viewticket' ticket.id %}">
                <button class="btn btn-primary">gedit
                    View Ticket >>
                </button>
            </a>
        </div>
    </div>
</div>

requests/templates/requests/ticket_view.html
{% extends 'requests/base.html' %}

{% block title %}View Ticket - {{ ticket.id }}{% endblock %}

{% block body %}
    <h1>Ticket {{ ticket.id }}</h1>
    <h3><b>Subject:&nbsp;</b>{{ ticket.subject }} | <b>Created by:&nbsp;</b>{{ ticket.creator }} | <b>Status: </b> {{ ticket.get_status_display }}</h3>

    <div class="container-fluid">
    <button class="btn btn-primary" data-toggle="collapse" data-target="#update" style="margin: 10px; margin-left: 0px;">Update Ticket >></button>

    <div class="panel panel-default collapse" id="update">
        <div class="panel-body">
            <form method="POST" action="">
                {% csrf_token %}
                {% include 'requests/form_template.html' %}
                <button class="btn btn-success" type="submit" style="float: right;">Submit</button>
            </form>
        </div>
    </div>
    </div>

    <div class="container-fluid">

        {% for update in ticket.updates.all %}
            <div class="panel panel-default">
            <div class="panel-heading">
                <strong>{{ update.user }}</strong>
                <span style="float:right;">
                    <span class="label label-{{ update.get_lbtype }}">{{ update.get_status_display }}</span>
                    {{ update.time }}
                </span>
            </div>
            <div class="panel-body">
                <p>{{ update.comment }}</p>
            </div>
        </div>
        {% endfor %}


        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>{{ ticket.creator }}</strong>
                <span style="float:right;">
                    {{ ticket.time }}
                </span>
            </div>
            <div class="panel-body">
                <p>{{ ticket.description }}</p>
            </div>
        </div>
    </div>
{% endblock %}

requests/templates/requests/tickets.html
{% extends 'requests/base.html' %}

{% block title %}Your Created Tickets{% endblock %}

{% block yours %}active{% endblock %}
{% block work %}{% endblock %}

{% block body %}
    <h1>Your Tickets</h1>
    <hr>

    <div class="container-fluid">
        <div class="row">

            {% for ticket in tickets %}
                {% include 'requests/render_ticket.html' %}
            {% endfor %}

        </div>
    </div>

{% endblock %}

requests/templates/requests/work.html
{% extends 'requests/base.html' %}

{% block title %}Tickets To Be Worked On{% endblock %}

{% block yours %}{% endblock %}
{% block work %}active{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="container" style="width: 20%; float: left; overflow: hidden;">
            <h2>Queues</h2>
            <hr>
            <ul class="nav nav-pills nav-stacked" style="max-height: 70vh;  overflow: auto;">
                {% for  queue in queues %}
                    <li><a data-toggle="pill" href="#{{ forloop.counter0 }}">{{ queue.name }}</a></li>
                {% endfor %}
            </ul>
        </div>

        <div class="container" style="width: 80%; float: right;">
            <h2>Tickets</h2>
            <hr>
            <div class="tab-content" style="max-height: 69vh;  overflow-y: auto; overflow-x: hidden;">
                {% for queue in queues %}
                    <div id="{{ forloop.counter0 }}" class="tab-pane fade in">
                        <div class="row">
                            {% for ticket in queue.get_open_tickets %}
                                {% include 'requests/render_ticket.html' %}
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}